//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_LAB_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int cost { get; set; }
        public int stock_balance { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
